version: '3.8'

services:
  web:
    build: .
    container_name: project-web
    ports:
      - "3000:3000"
    environment:
      - API_BASE_URL=${API_BASE_URL}
    networks:
      - project-network

networks:
  project-network:
    driver: bridge
